[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "nested_fit"
version = "5.1.1"
description = "The nested_fit package."

authors = [
    {name = "Martino Trassinelli"},
    {name = "Lune Maillard"},
    {name = "CÃ©sar Godinho"}
]

classifiers = [
    "Programming Language :: Fortran",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "License :: Free To Use But Restricted",
    "Operating System :: OS Independent"
]

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "scipy",
    "getdist",
    "tqdm"
]

[project.urls]
"Homepage" = "https://github.com/martinit18/nested_fit"
"Bug Tracker" = "https://github.com/martinit18/nested_fit/issues"
